#!/bin/bash
vimPluginPath=$HOME/.vim/bundle/

#Validate plugin path existence
if [ -d $vimPluginPath ]; then
  echo "Found $vimPluginPath"
else
  echo "$vimPluginPath NOT FOUND"
  exit $?
fi

#Special cases
specialCase() {

local array=(YouCompleteMe)

if [[ " ${array[*]} " == *"$1"* ]]; then
	echo "FOUND SPECIAL CASE: $1"
  eval ${1}
fi

}
#Special case: YouCompleteMe
YouCompleteMe() {
  ./install.py
}

#Update plugins
cd $vimPluginPath

for plugin in *; do
  cd "$plugin"
  git fetch --all
  git reset --hard origin/master
  specialCase "$plugin"
  cd ..
done

echo "===================DONE==================="
